### ISSUE TITLE
unexpected behaviour with custom tags

### ISSUE THREAD

**Issue by itenisz** [syntax-tree/hast-util-select#1]
Greetings!

I use this tool, with custom html like tree.
When i use a custom tag where "tagName": "title", i cannot get children tags, because they are stringified.

I know this tool is for standard html, but i like to use for my custom data structures.
So i cannot use "title" named tag, and i dont know which tag has similar problems.

Maybe this is the required behaviour for standard usage, and not fixable, but i just wanted to write here, if anybody would use custom tags, this could happen.

**Comment by ChristianMurphy** [comment]
> When i use a custom tag where "tagName": "title", i cannot get children tags, because they are stringified.

That is because `<title>` is not a custom tag.
It is a reserved tag in the HTML spec.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
https://html.spec.whatwg.org/multipage/semantics.html#the-title-element
https://www.w3.org/TR/html50/document-metadata.html#the-title-element

The parser is appropriately following the spec for what is valid content for `<title>`

> Content model:Text that is not inter-element whitespace.

If you are looking for a custom tag, and element that has at least one dash in the name will work.
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

For example `<custom-title>` will parse children. https://astexplorer.net/#/gist/c46c11e6a161646146d05411c2f9f7e3/ab19dcc938b0dfdf65cc0e06c81870acf9d79250

**Comment by ChristianMurphy** [comment]
If you are interested in parsing that will allow more flexibility in naming than the HTML spec, you may want to checkout or contribute to https://github.com/unifiedjs/ideas/issues/2

**Comment by wooorm** [comment]
There's also unist-util-select, which let's you select any node in the tree!
